name: Copybara Migration

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t copybara-image .

      - name: Run Copybara Migration
        run: |
          docker run --rm -v ${{ github.workspace }}:/app copybara-image migrate ./copy.bara.sky --force --init-history --git-committer-email "vemulas@gmail.com" --git-committer-name "Srikanth" --commands-timeout 12000s --repo-timeout=20000s
