name: Sync Repositories

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: vemulas19/practict  # Replace with your source repository
          ref: master  # Adjust the branch name as needed

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add target https://github.com/vemulas19/practict2.git
          git fetch origin
          git reset --hard origin/master
          git push https://vemulas19:${{ secrets.GH_PAT }}@github.com/vemulas19/practict2 master --force
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
